name: mik
version: '1.0'
main: org.encinet.mik.Mik
api-version: '1.21'
authors: [ Noctiro ]
dependencies:
  bootstrap:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true