name: mik
version: '1.0'
main: org.encinet.mik.Mik
loader: org.encinet.mik.MikLoader
api-version: '26.1'
authors: [ Noctiro ]
dependencies:
  bootstrap:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: false
    ViaVersion:
      load: BEFORE
      required: false
      join-classpath: true
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: false
    ViaVersion:
      load: BEFORE
      required: false
      join-classpath: true
